// Słownik kodów opakowań systemowych SUUS (dokumentacja, str. 16)
export const SUUS_PACKAGE_CODES = {
  BEC: "Beczka",
  BEL: "Bela",
  BIG: "Big bag",
  CH1: "Paleta chep 1/2",
  CH2: "Paleta chep 1/4",
  CHP: "Paleta chep",
  COL: "Colli (paczka standardowa)",
  DHP: "Paleta DHP",
  DOK: "Kontenerek DOK",
  DPL: "Pojemnik DPPL",
  EUR: "Paleta EUR",
  HB: "Hobok",
  JED: "Paleta jednorazowa",
  KAR: "Karton",
  LUZ: "Towar luzem",
  PAL: "Paleta inna",
  PLT: "Paleta przemysłowa",
  ROL: "Rolka",
  SKC: "Ciężka skrzynia",
  SKR: "Skrzynia",
  WCC: "Wózek kwiatowy",
  WIA: "Wiązka",
  WOR: "Worek",
};
